name: CI

on: 
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs: 
  build:
    name: Build Environment and Run Test Cases
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint:all
        
      - name: Unit Tests
        run: yarn test:all --silent

      - name: E2E Tests -- Playwright
        timeout-minutes: 20
        run: yarn test:e2e


      
        
